from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi_About(self, About):
        About.setObjectName("About")
        About.setEnabled(True)
        About.resize(470, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(About.sizePolicy().hasHeightForWidth())
        About.setSizePolicy(sizePolicy)
        About.setMinimumSize(QtCore.QSize(470, 350))
        About.setMaximumSize(QtCore.QSize(470, 350))
        self.label = QtWidgets.QLabel(parent=About)
        self.label.setGeometry(QtCore.QRect(10, 10, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=About)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=About)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 441, 20))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(parent=About)
        self.line.setGeometry(QtCore.QRect(20, 140, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(parent=About)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=About)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=About)
        self.label_6.setGeometry(QtCore.QRect(9, 260, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label.setText(_translate("About", "TV Zone Software"))
        self.label_2.setText(_translate("About", "Simple Labels"))
        self.label_3.setText(_translate("About", "version: 1.0.0 for vMix"))
        self.label_4.setText(_translate("About", "Copyright © 2023 TV Zone - MARCIN OSKO. All rights reserved."))
        self.label_5.setText(_translate("About", "Simple Labels is a straightforward app that solves the problem of implementing graphics in video productions. It allows you to easily organize data, save and load it, and safely pass it to the graphics engine while controlling its operation. Familiarize yourself with the free version of Simple Labels.\n"

"\n"
"The Licensor Site is currently located at:"))
        self.label_6.setText(_translate("About",
                                        "<a href=\"http://tvsimpleapps.com\">http://tvsimpleapps.com</a>"))
